name: MultiEco
main: org.fatecrafters.plugins.MultiEco
version: 1.1
author: Slayr288
website: http://Fatecrafters.org
description: Seperate economy between worlds.
softdepend: [Vault]
commands:
  multieco:
    description: Main commands.
    aliases: [meco, multie, mec]
permissions:
  multieco.reload:
    description: Reload Permission.
    default: op
  multieco.reset:
    description: Reset all of a worlds data.
    default: op
  multieco.help:
    description: Help menu.
    default: op
  multieco.commandblock.bypass:
    description: Bypass the command blocks.
    default: false